# TODO: bump content w/ auto-generation, e.g. via mypy (not found in typeshed collection)
#   or find already existing type sheds of https://lldb.llvm.org/python_api.html

class SBDebugger:
    @classmethod
    def Create(cls) -> "SBDebugger": ...
    def HandleCommand(self, command: str) -> None: ...
    def GetSelectedTarget(self) -> "SBTarget": ...

class SBTarget:
    def GetTriple(self) -> str: ...
    def GetPlatform(self) -> "SBPlatform": ...
    def GetExecutable(self) -> "SBFileSpec": ...

class SBPlatform:
    def GetTriple(self) -> str: ...

class SBFileSpec:
    def GetFilename(self) -> str: ...
    def GetDirectory(self) -> str: ...

debugger: SBDebugger
