# https://github.com/marketplace/actions/backporting-github-action#github-action
name: PR Backporting Manual

on: 
  workflow_dispatch:
    inputs:
      targetBranch:
        description: 'Target branch'
        required: true
        type: string
      pullRequest:
        description: 'Pull request'
        required: true 
        type: string
      dryRun:
        description: 'Dry run'
        required: false
        default: "false" 
        type: string

jobs:
  backporting:
    name: "Backporting"
    runs-on: ubuntu-latest
    permissions:
      contents: write # to allow pushing branches
      pull-requests: write # to allow creating pull requests
    steps:
      - name: Backporting
        uses: kiegroup/git-backporting@v4.8.6
        with:
          target-branch: ${{ inputs.targetBranch }}
          pull-request: ${{ inputs.pullRequest }}
          auth: ${{ secrets.GITHUB_TOKEN }}
          dry-run: ${{ inputs.dryRun }}
